# fly.toml app configuration file generated for skybridge on 2023-05-12T22:53:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# new updated
app = 'mw-skybridge'
primary_region = 'iad'

[env]
FLY_SWAP = 'true'
SKYBRIDGE_ALLOW_BACKFILL = 'true'
SKYBRIDGE_AUTH_PASSWORD = '1447096'
SKYBRIDGE_BASEURL = mw-skybridge.fly.dev
SKYBRIDGE_REQUIRE_AUTH_PASSWORD = 'true'
SKYBRIDGE_SECRET = '1447096'
SKYBRIDGE_SHOW_INDEX = 'true'

[[mounts]]
source = 'skybridge_data'
destination = '/app/database'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[http_service.concurrency]
type = 'requests'
hard_limit = 999999
soft_limit = 9999

[[http_service.checks]]
interval = '30s'
timeout = '5s'
grace_period = '30s'
method = 'GET'
path = '/api/v2/instance'

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
